//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAS.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_License
    {
        public int id { get; set; }
        public Nullable<int> BidderId { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        public string IDCard { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Modifier { get; set; }
        public string Name { get; set; }
        public Nullable<int> TracticsId { get; set; }
        public string Note { get; set; }
    }
}
