//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAS.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Performance_Record
    {
        public int Id { get; set; }
        public int BidderId { get; set; }
        public int RecordType { get; set; }
        public System.DateTime PeroformanceTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modifier { get; set; }
    }
}
